=== vambati/vambati/ActiveLearningforMT/data/p2p/translations.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:simpleType name="dateType">
    <xs:restriction base="xs:dateTime"/>
  </xs:simpleType>


  <xs:complexType name="transReqType">
    <xs:sequence>
      <xs:element name="source" type="xs:string"/>
    </xs:sequence>
    <xs:attribute name="id" type="xs:decimal" use="required"/>
  </xs:complexType>


  <xs:complexType name="transReqsType">
    <xs:sequence>
      <xs:element name="translation_request" minOccurs="1" maxOccurs="unbounded" type="transReqType"/>
    </xs:sequence>
  </xs:complexType>


  <xs:complexType name="targetsType">
    <xs:sequence>
      <xs:element name="target" minOccurs="1" maxOccurs="unbounded" type="xs:string"/>
    </xs:sequence>
  </xs:complexType>


  <xs:complexType name="translationType">
    <xs:sequence>
      <xs:element name="source" type="xs:string"/>
      <xs:element name="targets" type="targetsType" minOccurs="1" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attribute name="id" type="xs:decimal" use="required"/>
  </xs:complexType>


  <xs:complexType name="translationsType">
    <xs:sequence>
      <xs:element name="translation" maxOccurs="unbounded" type="translationType"/>
    </xs:sequence>
  </xs:complexType>


  <!-- 
       Format for sending requests for translations from BBN to CMU. Each
       'translation_request' element represents a separate request, for which the
       'source' element is the unit (sentence, phrase, etc) that needs to
       be translated.
    -->
  <xs:complexType name="requestType">
    <xs:sequence>
      <xs:element name="translation_requests" type="transReqsType"/>
    </xs:sequence>
    <xs:attribute name="id" type="xs:positiveInteger" use="required"/>
    <xs:attribute name="datetime" type="dateType" use="required"/>
  </xs:complexType>

  <xs:element name="request" type="requestType"/>



  <!--
      Format for sending a response to BBN's request from CMU to BBN.
      The 'source' elements are taken from the 'source' elements in the request.
      The 'target' element is its translation.  Note we can have multiple
      target elements for the same source element.   
    -->
  <xs:complexType name="responseType">
    <xs:sequence>
      <xs:element name="translations" type="translationsType"/>
    </xs:sequence>
    <xs:attribute name="id" type="xs:positiveInteger" use="required"/>
    <xs:attribute name="datetime" type="dateType" use="required"/>
  </xs:complexType>

  <xs:element name="response" type="responseType"/>



  <!--
      Format for sending an unsolicited set of translatiosn from CMU to BBN.
      These are translations which the BBN system did not ask for, but which 
      the CMU system thinks are valuable.
    -->
  <xs:complexType name="spontaneousType">
    <xs:sequence>
      <xs:element name="translations" type="translationsType"/>
    </xs:sequence>
    <xs:attribute name="id" type="xs:positiveInteger" use="required"/>
    <xs:attribute name="datetime" type="dateType" use="required"/>
  </xs:complexType>

  <xs:element name="spontaneous" type="spontaneousType"/>



</xs:schema>

=== vambati/vambati/ActiveLearningforMT/data/p2p/xml-spontaneous.xml
<?xml version="1.0" encoding="UTF-8"?>

<spontaneous id="789" datetime="2010-03-01T11:42:00" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.bbn.com/Translations C:\project\Speech\translations.xsd">
	<translations>
		<translation id="789.1">
			<source> word1 word2 wordnےندرھے </source>
			<targets>
				<target> word1 word2 wordnےندرھے </target>
				<target> word1 word2 wordn </target>
				<target> word1 word2 wordn </target>
				<target> word1 word2 wordn </target>
			</targets>
		</translation>
		<translation id="789.2">
			<source> word1 word2 wordn </source>
			<targets>
				<target> word1 word2 wordn </target>
				<target> word1 word2 wordn </target>
				<target> word1 word2 wordn </target>
			</targets>
		</translation>
	</translations>
</spontaneous>
